In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns
from torch.utils.data import DataLoader
from collections import deque
import numpy as np
import multiprocessing
import time
from numpy import array
import pandas as pd
import dask.dataframe as dd
from torch.utils.data import TensorDataset, DataLoader
torch.manual_seed(1)
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
samplesize = 5

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
!ls '/content/drive/My Drive/QueenslandDataset/'

 Case01.csv   Case08.csv   Case15.csv   Case22.csv   Case29.csv
 Case02.csv   Case09.csv   Case16.csv   Case23.csv   Case30.csv
 Case03.csv   Case10.csv   Case17.csv   Case24.csv   Case31.csv
 Case04.csv   Case11.csv   Case18.csv   Case25.csv   Case32.csv
 Case05.csv   Case12.csv   Case19.csv   Case26.csv  'Processed Data'
 Case06.csv   Case13.csv   Case20.csv   Case27.csv   uqvitalsignsdata
 Case07.csv   Case14.csv   Case21.csv   Case28.csv


In [2]:
ecg = []
ppg = []
ppg_offset = []
HR = []
sys = []
dias = []
offset_list = []
column_list = []
for i in range(1,31):
    case = pd.read_csv(f'/content/drive/My Drive/QueenslandDataset/Case{i:02d}.csv')
    case_copy = case.copy()
    print(case.shape)
    start = 0
    step = 100
    end = 1000
    while True:        
        flag = False
        offset = random.randint(-50,50)
        offset_list.append(offset)
        if(start+end>case.shape[0]):
            flag = True
        if start+offset<0:
          index = 0
        else:
          index = start+offset
        chunk = case[start:start+end]
        # ppg_row =chunk['Pleth'].to_numpy()
        # # ppg.append(ppg_row)
        # ppg_offset_row = case_copy[index:index+end]['Pleth'].to_numpy()
        # # print(start, end, offset )
        # # print("ppg",ppg_row)
        # # print("ppg_offset",ppg_offset_row)
        # # print("offset", offset)
        # ppg_offset.append(ppg_offset_row)
        # ecg_row =chunk['ECG'].to_numpy()
        # ecg.append(ecg_row)
        # hr_row = chunk['HR'].to_numpy()
        # HR.append(hr_row)
        # sys_row = chunk['SYS'].to_numpy()
        # sys.append(sys_row)
        dias_row = chunk['Dias'].to_numpy()
        dias.append(dias_row)
        # ecg.append(case['ECG'].to_numpy().tolist())
        # HR.append()
        # sys.append()
        # dias.append()
        # ppg_offset.append()
        start += step
        if flag:
            break
        # break
    # break

# ppg_df = pd.DataFrame(ppg)

(729600, 6)
(101376, 6)
(1498522, 6)
(876578, 6)
(1192551, 6)
(632116, 6)
(410034, 6)
(349389, 6)
(654832, 6)
(258457, 6)
(540660, 6)
(1771628, 6)
(594536, 6)
(533215, 6)
(158958, 6)
(1148642, 6)
(122266, 6)
(69427, 6)
(139674, 6)
(675123, 6)
(458547, 6)
(977954, 6)
(167733, 6)
(372308, 6)
(633856, 6)
(997822, 6)
(1538143, 6)
(446111, 6)
(730761, 6)
(368272, 6)


In [15]:
ppg

[array([0.3685 , 0.36801, 0.36728, 0.3663 , 0.36508, 0.36215, 0.35995,
        0.35726, 0.35458, 0.35043]),
 array([0.36728, 0.3663 , 0.36508, 0.36215, 0.35995, 0.35726, 0.35458,
        0.35043, 0.34945, 0.34872]),
 array([0.36508, 0.36215, 0.35995, 0.35726, 0.35458, 0.35043, 0.34945,
        0.34872, 0.34847, 0.34994]),
 array([0.35995, 0.35726, 0.35458, 0.35043, 0.34945, 0.34872, 0.34847,
        0.34994, 0.35189, 0.35458]),
 array([0.35458, 0.35043, 0.34945, 0.34872, 0.34847, 0.34994, 0.35189,
        0.35458, 0.35775, 0.36703]),
 array([0.34945, 0.34872, 0.34847, 0.34994, 0.35189, 0.35458, 0.35775,
        0.36703, 0.37289, 0.37998]),
 array([0.34847, 0.34994, 0.35189, 0.35458, 0.35775, 0.36703, 0.37289,
        0.37998, 0.38706, 0.40488])]

In [16]:
ecg

[array([-0.305, -0.31 , -0.325, -0.325, -0.33 , -0.355, -0.385, -0.395,
        -0.395, -0.38 ]),
 array([-0.325, -0.325, -0.33 , -0.355, -0.385, -0.395, -0.395, -0.38 ,
        -0.425, -0.45 ]),
 array([-0.33 , -0.355, -0.385, -0.395, -0.395, -0.38 , -0.425, -0.45 ,
        -0.435, -0.46 ]),
 array([-0.385, -0.395, -0.395, -0.38 , -0.425, -0.45 , -0.435, -0.46 ,
        -0.46 , -0.37 ]),
 array([-0.395, -0.38 , -0.425, -0.45 , -0.435, -0.46 , -0.46 , -0.37 ,
        -0.3  , -0.27 ]),
 array([-0.425, -0.45 , -0.435, -0.46 , -0.46 , -0.37 , -0.3  , -0.27 ,
        -0.235, -0.23 ]),
 array([-0.435, -0.46 , -0.46 , -0.37 , -0.3  , -0.27 , -0.235, -0.23 ,
        -0.24 , -0.185])]

In [17]:
ppg_offset

[array([], dtype=float64),
 array([0.35995, 0.35726, 0.35458, 0.35043, 0.34945, 0.34872, 0.34847,
        0.34994, 0.35189, 0.35458]),
 array([0.36801, 0.36728, 0.3663 , 0.36508, 0.36215, 0.35995, 0.35726,
        0.35458, 0.35043, 0.34945]),
 array([0.35458, 0.35043, 0.34945, 0.34872, 0.34847, 0.34994, 0.35189,
        0.35458, 0.35775, 0.36703]),
 array([0.35458, 0.35043, 0.34945, 0.34872, 0.34847, 0.34994, 0.35189,
        0.35458, 0.35775, 0.36703]),
 array([0.34847, 0.34994, 0.35189, 0.35458, 0.35775, 0.36703, 0.37289,
        0.37998, 0.38706, 0.40488]),
 array([0.34945, 0.34872, 0.34847, 0.34994, 0.35189, 0.35458, 0.35775,
        0.36703, 0.37289, 0.37998])]

In [18]:
offset

-2

In [30]:
ppg_df = pd.DataFrame(ppg)

In [31]:
ppg_df.to_csv('/content/drive/My Drive/QueenslandDataset/MovingWindowdata/ppg.csv')

In [3]:
ppg_offset_df = pd.DataFrame(ppg_offset)

In [4]:
ppg_offset_df.to_csv('/content/drive/My Drive/QueenslandDataset/MovingWindowdata/ppg_offset.csv')

In [5]:
offset_df = pd.DataFrame(offset_list)

In [6]:
offset_df.to_csv('/content/drive/My Drive/QueenslandDataset/MovingWindowdata/offset.csv')

In [3]:
ecg_df = pd.DataFrame(ecg)

In [4]:
ecg_df.to_csv('/content/drive/My Drive/QueenslandDataset/MovingWindowdata/ecg.csv')

In [6]:
hr_df = pd.DataFrame(HR)

In [7]:
hr_df.to_csv('/content/drive/My Drive/QueenslandDataset/MovingWindowdata/hr.csv')

In [4]:
sys_df = pd.DataFrame(sys)

In [5]:
sys_df.to_csv('/content/drive/My Drive/QueenslandDataset/MovingWindowdata/sys.csv')

In [3]:
dias_df = pd.DataFrame(dias)

In [4]:
dias_df.to_csv('/content/drive/My Drive/QueenslandDataset/MovingWindowdata/dias.csv')

In [ ]:
dias

[array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0.,  0.,  0., ..., 63., 63., 63.]),
 array([ 0

In [ ]:
ppg_df

0        1        2        3    ...      996      997      998      999
0       0.36850  0.36801  0.36728  0.36630  ...  0.53602  0.53602  0.53602  0.53602
1       0.40024  0.40464  0.40659  0.40708  ...  0.58291  0.58486  0.58486  0.58486
2       0.42808  0.42173  0.41563  0.41001  ...  0.32698  0.33358  0.33651  0.34066
3       0.48523  0.48303  0.48205  0.48107  ...  0.35971  0.35287  0.34994  0.34750
4       0.50379  0.50427  0.50501  0.50623  ...  0.46154  0.46520  0.46642  0.46740
...         ...      ...      ...      ...  ...      ...      ...      ...      ...
191233  0.50012  0.50012  0.50012  0.50012  ...  0.50012  0.50012  0.50012  0.50012
191234  0.50012  0.50012  0.50012  0.50012  ...  0.50012  0.50012  0.50012  0.50012
191235  0.50012  0.50012  0.50012  0.50012  ...  0.50012  0.50012  0.50012  0.50012
191236  0.50012  0.50012  0.50012  0.50012  ...  0.50012  0.50012  0.50012  0.50012
191237  0.50012  0.50012  0.50012  0.50012  ...      NaN      NaN      NaN      NaN

[191238 rows x 1000 columns]

In [ ]:
ppg_offset_df

0        1        2        3    ...      996      997      998      999
0     0.35189  0.35458  0.35775  0.36703  ...  0.53895  0.53895  0.53895  0.53895
1     0.29475  0.32088  0.33602  0.35629  ...  0.55580  0.55702  0.56117  0.56337
2     0.61661  0.61661  0.61661  0.61661  ...  0.51941  0.51380  0.50623  0.49768
3     0.44591  0.44908  0.45275  0.46056  ...  0.47179  0.47619  0.48034  0.48694
4     0.47497  0.47790  0.48083  0.48400  ...  0.47033  0.46764  0.46520  0.46300
...       ...      ...      ...      ...  ...      ...      ...      ...      ...
7283  0.68718  0.66764  0.63834  0.62882  ...  0.49988  0.49988  0.49988  0.49988
7284  0.39878  0.39170  0.38657  0.38144  ...  0.49988  0.49988  0.49988  0.49988
7285  0.28791  0.27814  0.27619  0.27521  ...  0.49988  0.49988  0.49988  0.49988
7286  0.28425  0.28400  0.28400  0.28400  ...  0.49988  0.49988  0.49988  0.49988
7287  0.31575  0.30965  0.30549  0.29963  ...      NaN      NaN      NaN      NaN

[7288 rows x 1000 columns]